default_language_version:
  python: python3.10

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: pretty-format-json
    args: ['--no-sort-keys']

- repo: https://github.com/PabloRMira/sql_formatter
  rev: 0.6.2
  hooks:
  - id: sql_formatter

- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black
    language_version: python3.10
    args:
    - --line-length=79
    - --include=*.py

- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    language_version: python3.10
    args:
    - --max-line-length=79
    - --max-complexity=18
    # - --select=B,C,E,F,W,T4,B9
    - --extend-ignore=E203,E266,E501,W503,F403,F401

ci:
  autofix_commit_msg: 🎨 [pre-commit.ci] Auto format from pre-commit.com hooks
  autoupdate_commit_msg: ⬆ [pre-commit.ci] pre-commit autoupdate
