version: "3.9"

services:
  postgres:
    image: postgres:14.5-alpine3.16
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT-5432}:${POSTGRES_PORT-5432}
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE-tochiquinho}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-password}
      POSTGRES_USER: ${POSTGRES_USER-user}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5

  service:
    container_name: service
    build:
      context: .
    ports:
      - ${PORT-80}:${PORT-80}
    depends_on:
      - postgres
    environment: 
      PORT: ${PORT-80}

volumes:
  postgres-db-volume: